name: Deploy via Self-hosted Runner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy to Server
        run: |
          echo "Starting deployment..."
          export PATH=$PATH:/home/marc/.nvm/versions/node/v22.18.0/bin/pm2
          cd /home/marc/DiscordBOT
          
          git pull origin main
          
          # python3 -m venv venv
          # source venv/bin/activate
          pip install -r /home/marc/DiscordBOT/budgetBOT/requirements.txt

          cd /home/marc/DiscordBOT/budgetBOT
          
          pm2 restart kaikei-bot || pm2 start budgetBOT.py --name kaikei-bot --interpreter python3
        
          pm2 save
          echo "Application is running in a pm2 session."